import { type Metadata } from "next";
import Script from "next/script";
import { Poppins } from "next/font/google";

import "../styles/spacings.css";
import "../styles/typography.css";
import "../styles/theme/tokens.css";
import "./globals.css";

import Header from "../components/Layout/Header";
import Footer from "../components/Layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="initialize-theme" strategy="lazyOnload">
          {`
            (function() {
              try {
                // Check for stored theme
                const storedTheme = localStorage.getItem("theme");
                const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

                // Determine initial theme
                const initialTheme = storedTheme || (prefersDark ? "dark" : "light");
                document.documentElement.setAttribute("data-theme", initialTheme);

                // Listen for system theme changes
                window
                  .matchMedia("(prefers-color-scheme: dark)")
                  .addEventListener("change", (e) => {
                    document.documentElement.setAttribute("data-theme", e.matches ? "dark" : "light");
                  });
              } catch (e) { 
                console.error('Error setting theme:', e); 
              }
            })();
          `}
        </Script>
      </head>
      <body className={`${poppins.variable}`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
