import styles from "./index.module.css";

const Privacy = () => {
  return (
    <div className={styles.page}>
      <div title={"Terms and Conditions"} className={styles.container}>
        <div className={styles.containerSection}>
          <h1>Privacy Policy</h1>
          <p
            dangerouslySetInnerHTML={{
              __html: `This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator`,
            }}
          />
        </div>
        <div className={styles.containerSection}>
          <h3>Interpretation</h3>
          <p>For the purposes of this Privacy Policy:</p>

          <ul>
            <li>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </li>
            <li>
              Affiliate means an entity that controls, is controlled by or is
              under common control with a party, where "control" means ownership
              of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing
              authority.
            </li>
            <li>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to fibi, Inc., 8605 Santa Monica Blvd
              West Hollywood, CA 90069 US.
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </li>
            <li>Country refers to: Delaware, United States</li>
            <li>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>Service refers to the Website.</li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Third-party Social Media Service refers to any website or any
              social network website through which a User can log in or create
              an account to use the Service.
            </li>
            <li>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
          </ul>
        </div>
        <div className={styles.containerSection}>
          <h3>Changes to this Privacy Policy</h3>
          <p
            dangerouslySetInnerHTML={{
              __html: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
              We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`,
            }}
          />
        </div>
      </div>
    </div>
  );
};

export default Privacy;
